# Dockerfile.dev (開発用)
FROM ruby:3.2.2

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs yarn

WORKDIR /my_app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v 2.4.13
RUN bundle install

COPY . .

# デフォルトコマンド（開発環境）
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-e", "development"]
