services:
  web:
    build: .
    command: bash -c "bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: my_app_development

  db:
    image: postgres:15
    platform: linux/arm64/v8  # ← M1/M2 Mac向け
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app_database
    ports:
      - "5432:5432"

